# Generated by Django 4.2.1 on 2023-06-09 08:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skilltube_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
