# Generated by Django 4.2.1 on 2023-05-30 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_video_title_video_video_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_caption',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_path',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=uuid.uuid4, upload_to='main/%y'),
        ),
    ]
