# Generated by Django 4.2.1 on 2023-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skilltube_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='THumbnails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thum_id', models.CharField(max_length=50)),
            ],
        ),
    ]
