# Generated by Django 4.2.1 on 2023-06-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnails',
            old_name='thum_id',
            new_name='thum_if',
        ),
    ]
