# Generated by Django 4.2.1 on 2023-06-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_thum_id_thumbnails_thum_if'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skilltube_users',
            new_name='User2',
        ),
        migrations.RenameField(
            model_name='thumbnails',
            old_name='thum_if',
            new_name='thum_id',
        ),
    ]
