# Generated by Django 4.2.1 on 2023-06-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
