# Generated by Django 4.2.1 on 2023-06-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_skilltube_users_user2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='Skilltube_Users',
        ),
        migrations.DeleteModel(
            name='THumbnails',
        ),
    ]
