# Generated by Django 4.2.1 on 2023-06-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user2_skilltube_users_delete_thumbnails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skilltube_Users',
            new_name='Skilltube_user',
        ),
    ]
