# Generated by Django 4.2.1 on 2023-06-09 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_skilltube_users_skilltube_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltube_user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='skilltube_user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skilltube_user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
