# Generated by Django 4.2.1 on 2023-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_skilltube_user_id_skilltube_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltube_user',
            name='user_id',
            field=models.UUIDField(default='74102fc18b9646a28db4b59d2bd0f783', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
