# Generated by Django 4.2.1 on 2023-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_skilltube_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltube_user',
            name='user_id',
            field=models.UUIDField(default='a1b2ec24185c4ed1a4d4f043241b3e97', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
