# Generated by Django 4.2.1 on 2023-06-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_skilltube_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltube_user',
            name='user_id',
            field=models.CharField(default='4cc09017f6ed49fb8753ebeaecba6854', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
