# Generated by Django 4.2.1 on 2023-06-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_skilltube_user_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skilltube_user',
        ),
    ]
