# Generated by Django 4.2.1 on 2023-06-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_skilltube_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skilltube_user',
        ),
    ]
