# Generated by Django 4.2.1 on 2023-06-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_skilltube_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('noob', 'Noob'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('masterclass', 'Masterclass')], default='beginner', max_length=20),
        ),
    ]
