# Generated by Django 4.2.1 on 2023-06-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_video_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes_count',
        ),
    ]
