# Generated by Django 4.2.1 on 2023-05-24 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('thumbnail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_title', models.CharField(max_length=255)),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_path', models.CharField(max_length=255)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thumbnail')),
            ],
        ),
    ]
